import Head from 'next/head';
import Image from 'next/image';
import { useEffect } from 'react'
//Material-UI
import TextField from '@mui/material/TextField';
import { useRouter } from 'next/router'

import CategoryChart from '../components/CategoryChart'
import ElectronicsChart from '../components/ElectronicsChart'
import CafeteriaChart from '../components/CafeteriaChart'
import OfficeAssetsChart from '../components/OfficeAssestChart'
import Layout from '../components/layout'

export default function Home() {

  const router = useRouter()

  useEffect(() => {
    let token = sessionStorage.getItem('Token')

    if(!token){
        router.push('/login')
    }
},[router])
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Layout>
        <div className='mt-9 text-center w-full flex flex-wrap justify-around gap-10'>
            <div className='w-[45%]'>
            <CategoryChart/>
            </div>
            <div className='w-[45%]'>
            <ElectronicsChart/>
            </div>
            <div className='w-[45%]'>
            <CafeteriaChart/>
            </div>
            <div className='w-[45%]'>
            <OfficeAssetsChart/>
            </div>    
        </div>
        </Layout>
      </main>
    </div>
  );
}
